name: Build
on:
  push:
  pull_request:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: hecrj/setup-rust-action@v1
    - uses: actions/checkout@v1
    - name: Check
      run: cargo check
    - name: Clippy
      run: cargo clippy
